spreadsheet docs, dhs links, yt links
UCD-DART/vectorsurv.org pull request #41
Opened 2024-06-23 23:30 UTC by RococoCoding

This PR:
- updates v5 arthro collection docs to include tabular input instructions
- updates generic dhs links to go to more specific zoonotic diseases/mosquitos/insects/wnv links
- adds links to youtube tutorials to related docs pages

2024-06-24 17:09 UTC, smranck commented on assets/images/docs/new_collection_species_form.png
Did we consider showing the same abundance counts for both images? If the species and counts are the same, it could be clearer that they have the same end result

2024-06-24 17:09 UTC, smranck commented on _docs/arthropod/v5/collection.md
> +If your screen size is larger than 768px, there are two input methods: A tabular input similar to the legacy form where you can update multiple abundances in one go and a mobile-friendly form where y
Could consider mentioning that it's for mobile before 768px. I think a lot of users will not know their screen size which could be confusing, but they should understand mobile.

2024-06-24 23:48 UTC, smranck commented on _docs/arthropod/v5/collection.md
> +  - After a species is selected, you can input counts for each sex/stage/condition column. ‘Σ F’ represents the total number of females for the row’s species across F-Mixed, F-Unfed, F-Bloodfed and F
Might make sense to mention that 0s are implied. The legacy docs say " It is not necessary to mark 0 counts as that is assumed when left blank or absent from the form."

2024-06-25 00:08 UTC, RococoCoding commented on assets/images/docs/new_collection_species_form.png
Great suggestion! I'll update them

2024-06-25 00:21 UTC, RococoCoding commented on _docs/arthropod/v5/collection.md
> +If your screen size is larger than 768px, there are two input methods: A tabular input similar to the legacy form where you can update multiple abundances in one go and a mobile-friendly form where y
Thanks, this reminded me I forgot to update that now it responds to changes in screen size without needing to refresh, but only if there are no live edits to the form (we don't want them to lose any work)

2024-06-28 23:08 UTC, smranck approved these changes

2024-07-24 22:05 UTC, tlvaldepena commented on _docs/arthropod/v5/collection.md
> +- **Tabular Input**
```suggestion
#### Tabular Input
```

2024-07-24 22:06 UTC, tlvaldepena commented on _docs/arthropod/v5/collection.md
> +- **Form Input**
```suggestion
#### Form Input
```

2024-07-24 22:09 UTC, tlvaldepena commented on _docs/site/v5/site.md
> +  - url: https://www.vectorsurv.org/docs/site/v5/walkthroughs/
```suggestion
  - url: https://vectorsurv.org/docs/site/v5/walkthroughs/
```

2024-07-24 22:15 UTC, tlvaldepena commented on _docs/tools/spatial-tools.md
> +Additional resource: [YouTube tutorial for Spatial Features](https://youtu.be/N6tjO9ptrD4).
I think this is the wrong link.

2024-07-24 22:17 UTC, tlvaldepena commented on _docs/tools/spatial-tools.md
When I merged Shawn's changes, I introduced a conflict here. Please resolve that conflict when you make the other changes.

2024-07-24 22:23 UTC, tlvaldepena requested changes
This looks great overall!

In the arthropod docs, many headers are also bolded (e.g., "### **Input Methods**"). Please remove the bold from headers. That will provide a more consistent look and allow us to use styles to adjust their presentation.

Also, please review the few minor suggestions I have made.

2024-07-24 22:45 UTC, tlvaldepena approved these changes

2024-07-24 22:46 UTC, merged